zsmalloc: use 3.10 version of zsmalloc
commit 796ce5a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Apr 23 18:30:48 2013 +0200

    staging/zsmalloc: don't use pgtable-mapping from modules

    Building zsmalloc as a module does not work on ARM because it uses
    an interface that is not exported:

    ERROR: "flush_tlb_kernel_range" [drivers/staging/zsmalloc/zsmalloc.ko] undefined!

    Since this is only used as a performance optimization and only on ARM,
    we can avoid the problem simply by not using that optimization when
    building zsmalloc it is a loadable module.

    flush_tlb_kernel_range is often an inline function, but out of the
    architectures that use an extern function, only powerpc exports
    it.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
    Cc: Seth Jennings <sjenning@linux.vnet.ibm.com>
    Cc: Nitin Gupta <ngupta@vflare.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit d95abbb
Author: Joerg Roedel <joro@8bytes.org>
Date:   Wed Mar 27 01:43:14 2013 +0100

    staging: zsmalloc: Fix link error on ARM

    Testing the arm chromebook config against the upstream
    kernel produces a linker error for the zsmalloc module from
    staging. The symbol flush_tlb_kernel_range is not available
    there. Fix this by removing the reimplementation of
    unmap_kernel_range in the zsmalloc module and using the
    function directly. The unmap_kernel_range function is not
    usable by modules, so also disallow building the driver as a
    module for now.

    Cc: stable <stable@vger.kernel.org>
    Signed-off-by: Joerg Roedel <joro@8bytes.org>
    Acked-by: Minchan Kim <minchan@kernel.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit 22b751c
Author: Mel Gorman <mgorman@suse.de>
Date:   Fri Feb 22 16:34:59 2013 -0800

    mm: rename page struct field helpers

    The function names page_xchg_last_nid(), page_last_nid() and
    reset_page_last_nid() were judged to be inconsistent so rename them to a
    struct_field_op style pattern.  As it looked jarring to have
    reset_page_mapcount() and page_nid_reset_last() beside each other in
    memmap_init_zone(), this patch also renames reset_page_mapcount() to
    page_mapcount_reset().  There are others like init_page_count() but as
    it is used throughout the arch code a rename would likely cause more
    conflicts than it is worth.

    [akpm@linux-foundation.org: fix zcache]
    Signed-off-by: Mel Gorman <mgorman@suse.de>
    Suggested-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

commit 0d145a5
Author: Seth Jennings <sjenning@linux.vnet.ibm.com>
Date:   Wed Jan 30 09:36:52 2013 -0600

    staging: zsmalloc: remove unused pool name

    zs_create_pool() currently takes a name argument which is
    never used in any useful way.

    This patch removes it.

    Signed-off-by: Seth Jennings <sjenning@linux.vnet.ibm.com>
    Acked-by: Nitin Gupta <ngupta@vflare.org>
    Acked-by: Rik van Riel <riel@redhat.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit 9915518
Author: Minchan Kim <minchan@kernel.org>
Date:   Mon Jan 28 10:00:08 2013 +0900

    staging: zsmalloc: Fix TLB coherency and build problem

    Recently, Matt Sealey reported he fail to build zsmalloc caused by
    using of local_flush_tlb_kernel_range which are architecture dependent
    function so !CONFIG_SMP in ARM couldn't implement it so it ends up
    build error following as.

      MODPOST 216 modules
      LZMA    arch/arm/boot/compressed/piggy.lzma
      AS      arch/arm/boot/compressed/lib1funcs.o
    ERROR: "v7wbi_flush_kern_tlb_range"
    [drivers/staging/zsmalloc/zsmalloc.ko] undefined!
    make[1]: *** [__modpost] Error 1
    make: *** [modules] Error 2
    make: *** Waiting for unfinished jobs....

    The reason we used that function is copy method by [1]
    was really slow in ARM but at that time.

    More severe problem is ARM can prefetch speculatively on other CPUs
    so under us, other TLBs can have an entry only if we do flush local
    CPU. Russell King pointed that. Thanks!
    We don't have many choices except using flush_tlb_kernel_range.

    My experiment in ARMv7 processor 4 core didn't make any difference with
    zsmapbench[2] between local_flush_tlb_kernel_range and flush_tlb_kernel_range
    but still page-table based is much better than copy-based.

    * bigger is better.

    1. local_flush_tlb_kernel_range: 3918795 mappings
    2. flush_tlb_kernel_range : 3989538 mappings
    3. copy-based: 635158 mappings

    This patch replace local_flush_tlb_kernel_range with
    flush_tlb_kernel_range which are avaialbe in all architectures
    because we already have used it in vmalloc allocator which are
    generic one so build problem should go away and performane loss
    shoud be void.

    [1] f553646, zsmalloc: add page table mapping method
    [2] https://github.com/spartacus06/zsmapbench

    Cc: stable@vger.kernel.org
    Cc: Dan Magenheimer <dan.magenheimer@oracle.com>
    Cc: Russell King <linux@arm.linux.org.uk>
    Cc: Konrad Rzeszutek Wilk <konrad@darnok.org>
    Cc: Nitin Gupta <ngupta@vflare.org>
    Cc: Seth Jennings <sjenning@linux.vnet.ibm.com>
    Reported-by: Matt Sealey <matt@genesi-usa.com>
    Signed-off-by: Minchan Kim <minchan@kernel.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit d662b8e
Author: Seth Jennings <sjenning@linux.vnet.ibm.com>
Date:   Fri Jan 25 11:46:18 2013 -0600

    staging: zsmalloc: make CLASS_DELTA relative to PAGE_SIZE

    Right now ZS_SIZE_CLASS_DELTA is hardcoded to be 16.  This
    creates 254 classes for systems with 4k pages. However, on
    PPC64 with 64k pages, it creates 4095 classes which is far
    too many.

    This patch makes ZS_SIZE_CLASS_DELTA relative to PAGE_SIZE
    so that regardless of the page size, there will be the same
    number of classes.

    Acked-by: Nitin Gupta <ngupta@vflare.org>
    Acked-by: Minchan Kim <minchan@kernel.org>
    Signed-off-by: Seth Jennings <sjenning@linux.vnet.ibm.com>
    Acked-by: Dan Magenheimer <dan.magenheimer@oracle.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit 4bbc0bc
Author: Davidlohr Bueso <davidlohr.bueso@hp.com>
Date:   Fri Jan 4 12:14:00 2013 -0800

    staging: zsmalloc: comment zs_create_pool function

    Just as with zs_malloc() and zs_map_object(), it is worth
    formally commenting the zs_create_pool() function.

    Signed-off-by: Davidlohr Bueso <davidlohr.bueso@hp.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit 0959c63
Author: Seth Jennings <sjenning@linux.vnet.ibm.com>
Date:   Wed Aug 8 15:12:17 2012 +0900

    zsmalloc: collapse internal .h into .c

    The patch collapses in the internal zsmalloc_int.h into
    the zsmalloc-main.c file.

    This is done in preparation for the promotion to mm/ where
    separate internal headers are discouraged.

    Signed-off-by: Seth Jennings <sjenning@linux.vnet.ibm.com>
    Signed-off-by: Minchan Kim <minchan@kernel.org>
    Acked-by: Nitin Gupta <ngupta@vflare.org>
    Reviewed-by: Konrad Rzeszutek Wilk <konrad.wilk@oracle.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit f553646
Author: Seth Jennings <sjenning@linux.vnet.ibm.com>
Date:   Wed Jul 18 11:55:56 2012 -0500

    staging: zsmalloc: add page table mapping method

    This patchset provides page mapping via the page table.
    On some archs, most notably ARM, this method has been
    demonstrated to be faster than copying.

    The logic controlling the method selection (copy vs page table)
    is controlled by the definition of USE_PGTABLE_MAPPING which
    is/can be defined for any arch that performs better with page
    table mapping.

    Signed-off-by: Seth Jennings <sjenning@linux.vnet.ibm.com>
    Acked-by: Minchan Kim <minchan@kernel.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit c60369f
Author: Seth Jennings <sjenning@linux.vnet.ibm.com>
Date:   Wed Jul 18 11:55:55 2012 -0500

    staging: zsmalloc: prevent mappping in interrupt context

    Because we use per-cpu mapping areas shared among the
    pools/users, we can't allow mapping in interrupt context
    because it can corrupt another users mappings.

    Signed-off-by: Seth Jennings <sjenning@linux.vnet.ibm.com>
    Acked-by: Minchan Kim <minchan@kernel.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit 6539a36
Author: Seth Jennings <sjenning@linux.vnet.ibm.com>
Date:   Wed Jul 18 11:55:54 2012 -0500

    staging: zsmalloc: s/firstpage/page in new copy map funcs

    firstpage already has precedent and meaning the first page
    of a zspage.  In the case of the copy mapping functions,
    it is the first of a pair of pages needing to be mapped.

    This patch just renames the firstpage argument to "page" to
    avoid confusion.

    Signed-off-by: Seth Jennings <sjenning@linux.vnet.ibm.com>
    Acked-by: Minchan Kim <minchan@kernel.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit b741851
Author: Seth Jennings <sjenning@linux.vnet.ibm.com>
Date:   Mon Jul 2 16:15:52 2012 -0500

    staging: zsmalloc: add mapping modes

    This patch improves mapping performance in zsmalloc by getting
    usage information from the user in the form of a "mapping mode"
    and using it to avoid unnecessary copying for objects that span
    pages.

    Signed-off-by: Seth Jennings <sjenning@linux.vnet.ibm.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit 166cfda
Author: Seth Jennings <sjenning@linux.vnet.ibm.com>
Date:   Mon Jul 2 16:15:51 2012 -0500

    staging: zsmalloc: add details to zs_map_object boiler plate

    Add information on the usage limits of zs_map_object()

    Signed-off-by: Seth Jennings <sjenning@linux.vnet.ibm.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit 1031233
Author: Seth Jennings <sjenning@linux.vnet.ibm.com>
Date:   Mon Jul 2 16:15:50 2012 -0500

    staging: zsmalloc: add single-page object fastpath in unmap

    Improve zs_unmap_object() performance by adding a fast path for
    objects that don't span pages.

    Signed-off-by: Seth Jennings <sjenning@linux.vnet.ibm.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit 5f60190
Author: Seth Jennings <sjenning@linux.vnet.ibm.com>
Date:   Mon Jul 2 16:15:49 2012 -0500

    staging: zsmalloc: remove x86 dependency

    This patch replaces the page table assisted object mapping
    method, which has x86 dependencies, with a arch-independent
    method that does a simple copy into a temporary per-cpu
    buffer.

    While a copy seems like it would be worse than mapping the pages,
    tests demonstrate the copying is always faster and, in the case of
    running inside a KVM guest, roughly 4x faster.

    Signed-off-by: Seth Jennings <sjenning@linux.vnet.ibm.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit 069f101
Author: Ben Hutchings <ben@decadent.org.uk>
Date:   Wed Jun 20 02:31:11 2012 +0100

    staging: zsmalloc: Finish conversion to a separate module

    ZSMALLOC is tristate, but the code has no MODULE_LICENSE and since it
    depends on GPL-only symbols it cannot be loaded as a module.  This in
    turn breaks zram which now depends on it.  I assume it's meant to be
    Dual BSD/GPL like the other z-stuff.

    There is also no module_exit, which will make it impossible to unload.
    Add the appropriate module_init and module_exit declarations suggested
    by comments.

    Reported-by: Christian Ohm <chr.ohm@gmx.net>
    References: http://bugs.debian.org/677273
    Cc: stable@vger.kernel.org # v3.4
    Signed-off-by: Ben Hutchings <ben@decadent.org.uk>
    Reviewed-by: Jonathan Nieder <jrnieder@gmail.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit b4b700c
Author: Seth Jennings <sjenning@linux.vnet.ibm.com>
Date:   Wed Jun 13 16:03:42 2012 -0500

    staging: zsmalloc: fix uninit'ed variable warning

    This patch fixes an uninitialized variable warning in
    alloc_zspage().  It also fixes the secondary issue of
    prev_page leaving scope on each loop iteration.  The only
    reason this ever worked was because prev_page was occupying
    the same space on the stack on each iteration.

    Signed-off-by: Seth Jennings <sjenning@linux.vnet.ibm.com>
    Reported-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit 2db51da
Author: Nitin Gupta <ngupta@vflare.org>
Date:   Sat Jun 9 17:41:14 2012 -0700

    staging: zsmalloc documentation

    Documentation of various struct page fields
    used by zsmalloc.

    Changes for v2:
    	- Regroup descriptions as suggested by Konrad

    Signed-off-by: Nitin Gupta <ngupta@vflare.org>
    Acked-by: Konrad Rzeszutek Wilk <konrad.wilk@oracle.com>
    Reviewed-by: Minchan Kim <minchan@kernel.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit c234434
Author: Minchan Kim <minchan@kernel.org>
Date:   Fri Jun 8 15:39:25 2012 +0900

    staging: zsmalloc: zsmalloc: use unsigned long instead of void *

    We should use unsigned long as handle instead of void * to avoid any
    confusion. Without this, users may just treat zs_malloc return value as
    a pointer and try to deference it.

    This patch passed compile test(zram, zcache and ramster) and zram is
    tested on qemu.

    changelog
      * from v2
    	- remove hval pointed out by Nitin
    	- based on next-20120607
      * from v1
    	- change zcache's zv_create return value
    	- baesd on next-20120604

    Cc: Dan Magenheimer <dan.magenheimer@oracle.com>
    Acked-by: Seth Jennings <sjenning@linux.vnet.ibm.com>
    Acked-by: Konrad Rzeszutek Wilk <konrad.wilk@oracle.com>
    Signed-off-by: Minchan Kim <minchan@kernel.org>
    Acked-by: Nitin Gupta <ngupta@vflare.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit 00a61d8
Author: Minchan Kim <minchan@kernel.org>
Date:   Thu May 3 15:40:40 2012 +0900

    staging: zsmalloc: add/fix function comment

    Add/fix the comment.

    Signed-off-by: Minchan Kim <minchan@kernel.org>
    Acked-by: Nitin Gupta <ngupta@vflare.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit 2e3b615
Author: Minchan Kim <minchan@kernel.org>
Date:   Thu May 3 15:40:39 2012 +0900

    staging: zsmalloc: rename zspage_order with zspage_pages

    zspage_order defines how many pages are needed to make a zspage.
    So _order_ is rather awkward naming. It already deceive Jonathan
    - http://lwn.net/Articles/477067/
    " For each size, the code calculates an optimum number of pages (up to 16)"

    Let's change from _order_ to _pages_ and some function names.

    Signed-off-by: Minchan Kim <minchan@kernel.org>
    Acked-by: Nitin Gupta <ngupta@vflare.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit d210267
Merge: 69964ea 5bb196a
Author: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Date:   Wed May 2 11:48:07 2012 -0700

    Merge 3.4-rc5 into staging-next

    This resolves the conflict in:
    	drivers/staging/vt6656/ioctl.c

    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit a27545b
Author: Minchan Kim <minchan@kernel.org>
Date:   Wed Apr 25 15:23:09 2012 +0900

    zsmalloc: use PageFlag macro instead of [set|test]_bit

    MM code always uses PageXXX to handle page flags.
    Let's keep the consistency.

    Signed-off-by: Minchan Kim <minchan@kernel.org>
    Acked-by: Nitin Gupta <ngupta@vflare.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Change-Id: I542f0b9eaf0264e1c9e38f9669fec8ea0debae7c
Signed-off-by: Larry Bassel <lbassel@codeaurora.org>
Signed-off-by: Francisco Franco <franciscofranco.1990@gmail.com>